services:
  - type: web
    name: whatsapp-analyzer
    env: python
    buildCommand: pip install -r web_app/requirements.txt
    startCommand: cd web_app && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 