services:
  - type: web
    name: whatsapp-analyzer
    env: python
    buildCommand: pip install -e .
    startCommand: python -m src.web.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8000 