name: whatsapp-analyzer
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/whatsapp-analyzer
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  - path: /analyze 